name: CloudCore-Lobbybased
main: ch.cloudcraft.cloudcore.Main
author: HopeDev
version: 1.2.2
description: A generic default description
commands:
  gamemode:
    description: gamemode
    aliases: [gm]
  gm0:
    aliases: [gms]
  gm1:
    aliases: [gmc]
  gm2:
    aliases: [gma]
  gm3:
    aliases: [gmspc]
  fly:

  lobby:
  build:
  kickall:
  testscoreboard:

